import type { SymposiumEvent } from "../types";

/**
 * ELVARIX'26 — Event Selection page data.
 *
 * This page shows these 8 events directly from this file instead of fetching
 * them from the backend API. That's deliberate: the Event Selection page must
 * always render correctly regardless of whether a backend is deployed/reachable.
 *
 * To edit an event's name, place, time, or participation type, just edit the
 * objects below — no backend or database involved for this page.
 *
 * Paper Presentation and E-Sports are the two actual Team registrations
 * (max team size below, used by the real Team Registration step). Every
 * other event is Individual — their maxTeamSize is fixed at 1 purely so the
 * Team Size row in the event details display reads "1" instead of falling
 * back to "To be announced".
 */
export const DEFAULT_MAX_TEAM_SIZE = 4;

// ELVARIX'26 is confirmed for 23 September 2026 — every event uses this date.
export const EVENT_DATE = "2026-09-23";

export const EVENT_SELECTION_EVENTS: SymposiumEvent[] = [
  {
    _id: "paper-presentation",
    slug: "paper-presentation",
    eventName: "Paper Presentation",
    category: "Technical",
    description: "",
    participationType: "Team",
    maxTeamSize: DEFAULT_MAX_TEAM_SIZE,
    date: EVENT_DATE,
    time: "11:00 AM – 1:00 PM",
    venue: "Auditorium",
    registrationFee: null,
    maxParticipants: null,
    registeredCount: 0,
    status: "open",
    rules: [
      "Team size: 1 to 4 members.",
      "Maximum 4 members are allowed per team.",
      "All team members must participate in the presentation.",
      "Every team member should be involved in presenting the paper.",
      "Judges will evaluate the presentation based on knowledge and understanding of the topic, content quality, relevance and clarity, presentation skills, communication, team participation, ability to answer questions, and overall performance.",
    ],
  },
  {
    _id: "blind-coding",
    slug: "blind-coding",
    eventName: "Blind Coding",
    category: "Technical",
    description: "",
    participationType: "Individual",
    maxTeamSize: 1,
    date: EVENT_DATE,
    time: "11:00 AM – 1:00 PM",
    venue: "Lab 1",
    registrationFee: null,
    maxParticipants: null,
    registeredCount: 0,
    status: "open",
    rules: [
      "Individual participation only — Team Size: 1.",
      "Participants must solve the given coding problem within the specified time limit.",
      "Only the permitted programming language(s) and environment/tools may be used.",
      "Use of the internet, AI tools, or outside help during the round is not allowed.",
      "Judging is based on correctness, logic, and problem-solving approach.",
      "Any form of malpractice will lead to disqualification.",
    ],
  },
  {
    _id: "ui-ux-design",
    slug: "ui-ux-design",
    eventName: "UI/UX Design",
    category: "Technical",
    description: "",
    participationType: "Individual",
    maxTeamSize: 1,
    date: EVENT_DATE,
    time: "11:00 AM – 1:00 PM",
    venue: "Lab 2",
    registrationFee: null,
    maxParticipants: null,
    registeredCount: 0,
    status: "open",
    rules: [
      "Individual participation only — Team Size: 1.",
      "Participants must design a UI/UX solution for the given problem statement within the allotted time.",
      "The design must be original work created during the event.",
      "Judging considers creativity, usability, and visual clarity.",
      "Participants must be ready to briefly present and explain their design.",
      "Any pre-made or plagiarized design will lead to disqualification.",
    ],
  },
  {
    _id: "tech-quiz",
    slug: "tech-quiz",
    eventName: "Tech Quiz",
    category: "Technical",
    description: "",
    participationType: "Individual",
    maxTeamSize: 1,
    date: EVENT_DATE,
    time: "11:00 AM – 1:00 PM",
    venue: "3rd Year Classroom",
    registrationFee: null,
    maxParticipants: null,
    registeredCount: 0,
    status: "open",
    rules: [
      "Individual participation only — Team Size: 1.",
      "The quiz will be conducted in multiple rounds covering technical topics.",
      "Each question must be answered within the given time limit.",
      "Scoring is based on accuracy and speed of response.",
      "Use of mobile phones or outside help during the quiz is not allowed.",
      "The organizers'/judges' decision on scoring and results will be final.",
    ],
  },
  {
    _id: "on-spot-video-editing",
    slug: "on-spot-video-editing",
    eventName: "On Spot Video Editing",
    category: "Non-Technical",
    description: "",
    participationType: "Individual",
    maxTeamSize: 1,
    date: EVENT_DATE,
    time: "11:00 AM – 3:00 PM",
    venue: "College Campus",
    registrationFee: null,
    maxParticipants: null,
    registeredCount: 0,
    status: "open",
    rules: [
      "Individual participation only — Team Size: 1.",
      "Only the footage/material provided or captured on the spot may be used.",
      "Editing must be completed within the specified time limit using the permitted software.",
      "The final video must be original work created during the event.",
      "Judging is based on creativity, editing quality, and storytelling.",
      "Any pre-edited or pre-prepared content will lead to disqualification.",
    ],
  },
  {
    _id: "word-dump",
    slug: "word-dump",
    eventName: "Word Dump",
    category: "Non-Technical",
    description: "",
    participationType: "Individual",
    maxTeamSize: 1,
    date: EVENT_DATE,
    time: "2:30 PM – 3:00 PM",
    venue: "Auditorium",
    registrationFee: null,
    maxParticipants: null,
    registeredCount: 0,
    status: "open",
    rules: [
      "Individual participation only — Team Size: 1.",
      "Participants take part in a word-based game/activity within a fixed time limit.",
      "Each participant must play within their allotted turn/time.",
      "Scoring follows the rules explained by the organizers before the round.",
      "Any unfair means, such as prior collusion or outside help, is not allowed.",
      "The organizers'/judges' decision will be final in case of any dispute.",
    ],
  },
  {
    _id: "corporate-walk",
    slug: "corporate-walk",
    eventName: "Corporate Walk",
    category: "Non-Technical",
    description: "",
    participationType: "Individual",
    maxTeamSize: 1,
    date: EVENT_DATE,
    time: "11:00 AM – 2:30 PM",
    venue: "Reading Hall",
    registrationFee: null,
    maxParticipants: null,
    registeredCount: 0,
    status: "open",
    rules: [
      "Individual participation only — Team Size: 1.",
      "Participants must walk based on the theme announced for the event.",
      "Judging is based on presentation, confidence, creativity, and theme relevance.",
      "Outfits/themes must be appropriate and college-friendly.",
      "Any props or accessories used must be safe, and pre-approved if required.",
      "The judges' decision on scoring will be final.",
    ],
  },
  {
    _id: "e-sports",
    slug: "e-sports",
    eventName: "E-Sports",
    category: "Non-Technical",
    description: "Game options: Free Fire / PUBG, Football.",
    participationType: "Team",
    maxTeamSize: DEFAULT_MAX_TEAM_SIZE,
    date: EVENT_DATE,
    time: "1:45 PM – 3:15 PM",
    venue: "Reading Hall",
    registrationFee: null,
    maxParticipants: null,
    registeredCount: 0,
    status: "open",
    gameOptions: ["Free Fire / PUBG", "Football"],
    rules: [
      "Team size: 1 to 4 members.",
      "Maximum 4 members are allowed per team.",
      "Each team selects one game at registration: Free Fire / PUBG, or Football.",
      "Participants must use their own phones/devices for Free Fire / PUBG.",
      "The winner will be determined based on the official in-game/match result and the tournament outcome.",
      "Fair play is mandatory — all team members are expected to participate and follow tournament conduct rules.",
    ],
  },
];
